#define MICROPY_HW_BOARD_NAME "M5Stack Tough"
#define MICROPY_HW_MCU_NAME "ESP32"

#define MODULE_AXP192_ENABLED (1)
#define MODULE_BM8563_ENABLED (1)
#define MODULE_FT6336_ENABLED (1)
#define MODULE_ILI9341_ENABLED (1)
